ENH: g5_modules updated for Hortense and cleanup for EOL Breniac

diff --git a/GEOSldas/build_scripts/g5_modules b/GEOSldas/build_scripts/g5_modules
--- a/GEOSldas/build_scripts/g5_modules
+++ b/GEOSldas/build_scripts/g5_modules
@@ -1,29 +1,34 @@
 #!/bin/csh -f
 
-set basedir_version = v6.2.8
+set basedir_version = v6.2.13
 
 set node = `uname -n`
 module purge
-if (($node =~ r0* ) || ($node =~ login* )) then
-    echo "Loading modules for Tier-1 (broadwell)..."
-    set basedir_path = /scratch/leuven/projects/lt1_2020_es_pilot/project_input/ldas/GEOSldas_libraries
-    module unuse /apps/leuven/broadwell/2016a/modules/all
-    module unuse /apps/leuven/broadwell/2018a/modules/all
-else if (($node =~ r1* )) then
-    echo "Loading modules for Tier-1 (skylake)..."
-    set basedir_path = /scratch/leuven/projects/lt1_2020_es_pilot/project_input/ldas/GEOSldas_libraries
-    module unuse /apps/leuven/skylake/2016a/modules/all
-    module unuse /apps/leuven/skylake/2018a/modules/all
-else
+if ( $node =~ tier2* ) then
     echo "Loading modules for Tier-2..."
     set basedir_path = /staging/leuven/stg_00024/GEOSldas_libraries
     module unuse /apps/leuven/skylake/2018a/modules/all
     module unuse /apps/leuven/cascadelake/2018a/modules/all
     module unuse /apps/leuven/cascadelake/2019b/modules/all
     module use /apps/leuven/skylake/2019b/modules/all
+    module load foss flex Bison CMake Autotools texinfo gomkl Python/2.7.16-GCCcore8.3.0
+else if ( $node =~ *dodrio* ) then 
+    echo "Loading modules for Hortense Tier-1..."
+    set basedir_path = /dodrio/scratch/projects/2022_200/project_input/ldas/GEOSldas_libraries
+    module --force purge
+    module load cluster/dodrio/cpu_rome
+    module load foss flex/2.6.4-GCCcore-11.3.0 
+    module load Bison 
+    module load CMake 
+    module load Autotools 
+    module load texinfo 
+    module load Python/2.7.18-GCCcore-11.3.0-bare 
+    module load libtirpc/1.3.2-GCCcore-11.3.0 
+    module load imkl/2022.1.0
+else 
+    echo "Platform not found ... exit"
+    exit 1
 endif
 
-module load foss flex Bison CMake Autotools texinfo gomkl Python/2.7.16-GCCcore-8.3.0
-
-setenv BASEDIR $basedir_path/ESMA-Baselibs-$basedir_version/src
+setenv BASEDIR $basedir_path/ESMA-Baselibs-$basedir_version
 setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:$BASEDIR/Linux/lib
